# Generated by Django 4.0.3 on 2022-04-08 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise_date', models.DateField()),
                ('exercise_time', models.TimeField(default=django.utils.timezone.now)),
                ('callsign', models.CharField(max_length=20)),
                ('strength', models.PositiveSmallIntegerField()),
                ('work_position', models.CharField(choices=[('ic1', 'ic1'), ('ci2', 'ic2'), ('ic3', 'ic3'), ('ic4', 'ic4'), ('ic5', 'ic5'), ('ic6', 'ic6'), ('ic7', 'ic7'), ('ic8', 'ic8'), ('ic9', 'ic9'), ('ic10', 'ic10')], max_length=20, null=True)),
                ('radio', models.CharField(help_text='FXXX or xxx.xxx', max_length=50, verbose_name='R/S')),
                ('frequency', models.CharField(max_length=20, verbose_name='Fxxx')),
                ('net', models.CharField(choices=[('NO', 'NO'), ('A00.025', 'Net 0'), ('A00.125', 'Net 1'), ('A00.225', 'Net 2'), ('A00.325', 'Net 3'), ('A00.425', 'Net 4'), ('A00.525', 'Net 5')], max_length=20, null=True, verbose_name='NET')),
                ('net_success', models.BooleanField(default=False)),
                ('crypto', models.BooleanField(default=False)),
                ('area_1', models.CharField(max_length=20)),
                ('area_1_from', models.CharField(max_length=20)),
                ('area_1_to', models.CharField(max_length=20)),
                ('area_2', models.CharField(blank=True, max_length=20)),
                ('area_2_from', models.CharField(blank=True, max_length=20)),
                ('area_2_to', models.CharField(blank=True, max_length=20)),
                ('e30a', models.IntegerField(help_text='BFM', verbose_name='E-30a')),
                ('e30b', models.IntegerField(blank=True, null=True, verbose_name='E-30b')),
                ('e31a', models.IntegerField(blank=True, null=True, verbose_name='E-31a')),
                ('e31b', models.IntegerField(blank=True, null=True, verbose_name='E-31b')),
                ('e32', models.IntegerField(blank=True, null=True, verbose_name='E-32')),
                ('e33', models.IntegerField(blank=True, null=True, verbose_name='E-33')),
                ('e34', models.IntegerField(blank=True, null=True, verbose_name='E-34')),
                ('e35a', models.IntegerField(blank=True, null=True, verbose_name='E-35a')),
                ('e35b', models.IntegerField(blank=True, null=True, verbose_name='E-35b')),
                ('e36a', models.IntegerField(blank=True, null=True, verbose_name='E-36a')),
                ('e36b', models.IntegerField(blank=True, null=True, verbose_name='E-36b')),
                ('e37a', models.IntegerField(blank=True, null=True, verbose_name='E-37a')),
                ('e37b', models.IntegerField(blank=True, null=True, verbose_name='E-37b')),
                ('e38', models.IntegerField(blank=True, null=True, verbose_name='E-38')),
                ('e83', models.IntegerField(blank=True, null=True, verbose_name='E-83')),
                ('remarks', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Content should be at least 2 characters long!')])),
                ('ic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
